version: '3'

services:
  api:
    image: api
    build:
      context: ./../api
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=api.sdfg.local

  web:
    image: web
    build:
      context: ./../web
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=sdfg.local

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro