version: '3'

services:
  api:
    image: api-demo2
    container_name: api-demo2
    build:
      context: ./../api
      dockerfile: Dockerfile

  web:
    image: web-demo2
    container_name: web-demo2
    build:
      context: ./../web
      dockerfile: Dockerfile
    ports:
      - 8082:80
    environment:
      - API_URL=http://api/api/moviequote