version: '3'

services:
  api:
    image: api
    container_name: api
    build:
      context: ./../api
      dockerfile: Dockerfile

  web:
    image: web
    container_name: web
    build:
      context: ./../web
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - API_URL=http://api/api/moviequote