version: '2'

services:
  api:
    image: api
    container_name: api
    build:
      context: ./../api
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=localhost/api

  web:
    image: web
    container_name: web
    build:
      context: ./../web
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=localhost
      - API_URL=http://localhost/api/moviequote

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro