version: '3'

services:
  api:
    image: api-demo3
    container_name: api-demo3
    build:
      context: ./../api
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=localhost/api

  web:
    image: web-demo3
    container_name: web-demo3
    build:
      context: ./../web
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=localhost
      - API_URL=http://localhost/api/moviequote

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: reverse-proxy-demo3
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro